### ISSUE TITLE
مشکل در اتصال

### ISSUE THREAD

**Issue by shell32** [freedomeofdevelopers/fod#114]
در حال حاضر سرویس از کار افتاده.لطفا علت را بفرمایید

**Comment by behdad222** [comment]
@oraclenik

**Comment by behdad222** [comment]
@shell32 الان چطور هست؟

**Comment by shell32** [comment]
@behdad222 
درست شد.سپاس

**Comment by Bha91** [comment]
سلام 
الان سرویس قطع هست ؟ یا من اشتباه تنظیم کردم؟

**Comment by behdad222** [comment]
این کامنت رو من دارم با ترافیکی که از fod میگزره میزارم و این یعنی داره درست کار میکنه

@Bha91
