### ISSUE TITLE
PostMan Native App

### ISSUE THREAD

**Issue by Saeedtrs** [freedomeofdevelopers/fod#127]
نرم افزار نیتیو پستمن رو هم اضافه کنید بدون فیلترشکن کار نمیکنه

**Comment by behdad222** [comment]
postman?
اون به کجا قرار هست ریکوست بزنه؟

**Comment by Saeedtrs** [comment]
فرقی نمیکنه سرور داخلی باشه خارجی باشه بدون فیلترشکن رکوست نمیزنه و البته اصلا باز نمیشه

**Comment by behdad222** [comment]
@Saeedtrs من فکر کنم اشتباهی تو کارتون وجود داره
من همچین مشکلی ندارم
