### ISSUE TITLE
Problem with gradle.org

### ISSUE THREAD

**Issue by EAliakbar** [freedomeofdevelopers/fod#143]
I think there is a server problem with *.gradle.org

Proxifire Log:
[04.19 00:36:52] studio64.exe *64 - services.gradle.org:443 error : Could not connect through proxy fod.backtory.com:8118 - Proxy server cannot establish a connection with the target, status code 503

After removing gradle rule from proxifire problem solved, so two things:
1-There is no need to proxy gradle.org
2-Fod server have problem this website

For recreating this problem you can try downloading this link
https://services.gradle.org/distributions/gradle-4.7-all.zip

**Comment by oraclenik** [comment]
Hey I just downloaded the file and it worked ok
I'll close this issue, if the problem still there please  open issue again.
;)
