### ISSUE TITLE
add jwplayer.com

### ISSUE THREAD

**Issue by worldsnas** [freedomeofdevelopers/fod#154]
سلام 
بسیار ممنونم از این سروری که تهیه کرده اید 
لطفا jwplayer.com و mvn.jwplayer.com را هم به لیست سرور های مجازتون اضافه کنید
با تشکر

**Comment by behdad222** [comment]
@oraclenik close this issue

**Comment by worldsnas** [comment]
it's not been added yet. why should we close it?

**Comment by oraclenik** [comment]
چرا توی لیست هست
خط ۵۳
با همه ساب دامین ها
