### ISSUE TITLE
add https://play.google.com/store?hl=en

### ISSUE THREAD

**Issue by sinarahimpoor** [freedomeofdevelopers/fod#163]
همون طور که میدونید تعداد اپ هایی که برای کشور ایران نمایش داده میشه بسار محدوده و قابل دانلود هم نیستن

 در صورتی که با ای پی غیر ایران از سایت یا ای پی ای استفاده کرد محدودیت ها رفع میشود

اگر این سایت قابل اضافه کردن نباشه امکان استفاده از سرویس پولی بکتوری برای این منظور هست ؟

**Comment by oraclenik** [comment]
سلام دوست عزیز
FoD 
 به بکتوری وابستگی نداره و به صورت یک ارگان غیرانتفاعی فعالیت می کنه

**Comment by sinarahimpoor** [comment]
ممنونم
اجرتون با خدا
