### ISSUE TITLE
Write a step-by-step guide for Linux users

### ISSUE THREAD

**Issue by sorousht** [freedomeofdevelopers/fod#94]
Hi

I was wondering if we could write a guide for Linux users. I spent a few hours to find the solution!
Here is a walk-through:
1. Install Privoxy on the local machine as a proxy server
2. Forward all entries in `domains` file to `fod.backtory.com:8118` 
3. Apply the proxy system-wide.

**Comment by behdad222** [comment]
also you can use Proxychains
